### ISSUE TITLE
0x8b error

### ISSUE THREAD

**Issue by suliveevil** [jml/obsidian-to-org#5]
```shell
python3 __main__.py ~/ob ~/obe
Converted /Users/suliveevil/ob/我的笔记.md to 我的笔记.org
Copying from /Users/suliveevil/ob/.DS_Store to /Users/suliveevil/obe/.DS_Store
Converted /Users/suliveevil/ob/README.md to README.org
Converted /Users/suliveevil/ob/URL Schemes 与 Alfred 和 Eudic 的结合.md to URL Schemes 与 Alfred 和 Eudic 的结合.org
Converted /Users/suliveevil/ob/macOS小记-AppleScript、BetterTouchTool、Keyboard Maestro.md to macOS小记-AppleScript、BetterTouchTool、Keyboard Maestro.org
Converted links in /Users/suliveevil/obe/URL Schemes 与 Alfred 和 Eudic 的结合.org
Traceback (most recent call last):
  File "/Users/suliveevil/Documents/GitHub/obsidian-to-org/src/obsidian_to_org/__main__.py", line 197, in <module>
    convert_directory()
  File "/Users/suliveevil/Documents/GitHub/obsidian-to-org/src/obsidian_to_org/__main__.py", line 189, in convert_directory
    contents = org_path.read_text()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1135, in read_text
    return f.read()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 92: invalid start byte
```

**Comment by AndrewNatoli** [comment]
There might be a file in your Obsidian vault that isn't Markdown. For example, the presence of `.DS_Store` files on a Mac (I see you had one copied in the output you shared) can cause this script to fail.

**Comment by suliveevil** [comment]
I gave up converting from obsidian to org……
